name: Deploy client nuget

on:
  push:
    tags: "client-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release src/client/Lykke.Service.SmartOrderRouter.Client /p:Version=${GITHUB_REF#refs/tags/client-}
    - name: Publish the package to GPR
      run: dotnet nuget push src/client/Lykke.Service.SmartOrderRouter.Client/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}